application: pandt-1050
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /create_user
  script: create_user.php
  secure: always
  
- url: /login_user
  script: login_user.php
  secure: always

- url: /save_score
  script: save_score.php
  secure: always
  
- url: /watched_ads
  script: watched_ads.php
  secure: always

- url: /retrieve_coins
  script: retrieve_coins.php
  secure: always
  
- url: /purchase
  script: purchase.php
  secure: always
  
- url: /revive_streaks
  script: revive_streaks.php
  secure: always